/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/bottle_v10.glb -o src/components/Bottle.jsx 
*/

import {useRef, useMemo, useEffect} from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';
import { label, log } from 'three/tsl';

const MODEL_PATH = '/3d_viewer/models/bottle_v10.glb';

export function Bottle({
  scale = 0.7,
  position = [0, 0, 0],
  rotation = [0, 0, 0],
  bodyColor = '#ffffff',
  labelVisible = true,
  customLabelUrl = null,  
  logoVisible = true,
  customLogoUrl = null, 
  ...props}) {
  const { nodes, materials } = useGLTF(MODEL_PATH);
  const group = useRef();
  const labelRef = useRef();
  const logoRef = useRef();

  const bodyMaterial = useMemo(() => new THREE.MeshStandardMaterial({
    color: bodyColor,
    metalness: 0.1,
    roughness: 0.5,
    side: THREE.DoubleSide,
  }), [bodyColor]);
  
  const baseLogoMaterial = useMemo(() => new THREE.MeshBasicMaterial({
    transparent: true,
    side: THREE.DoubleSide,
    depthWrite: false,
    opacity: 1.0,
  }), []);

  const baseLabelMaterial = useMemo(() => {
    const material = materials.mat0.clone();
    material.transparent = true;
    material.side = THREE.DoubleSide;
    material.depthWrite = false;
    material.needsUpdate = true;
    material.opacity = 1.0;
    return material;
  }, [materials]);

  useEffect(() => {
    if (customLabelUrl && labelRef.current) {
      const textureLoader = new THREE.TextureLoader();
      textureLoader.load(customLabelUrl, (texture) => {
        console.log("Custom label texture loaded:", texture);
        texture.colorSpace = THREE.SRGBColorSpace;
        texture.flipY = false;
        texture.needsUpdate = true;
        texture.wrapS = texture.wrapT = THREE.RepeatWrapping;
        texture.repeat.set(1, 2);
        texture.offset.set(-0.5, -0.5);

        const customeMaterial = new THREE.MeshBasicMaterial({
          map: texture,
          transparent: true,
          side: THREE.DoubleSide,
        });
        if(labelRef.current) {
          labelRef.current.material = customeMaterial;
        }
      });
    }else if(labelRef.current) {
      labelRef.current.material = baseLabelMaterial;
    }
  }, [customLabelUrl, baseLabelMaterial]); 

  useEffect(() => {
    if (customLogoUrl && logoRef.current) {
      const textureLoader = new THREE.TextureLoader();
      textureLoader.load(customLogoUrl, (texture) => {
        texture.colorSpace = THREE.SRGBColorSpace;
        texture.flipY = false;
        texture.needsUpdate = true;

        const customLogoMaterial = new THREE.MeshBasicMaterial({
          map: texture,
          transparent: true,
          side: THREE.DoubleSide,
        });
        if(logoRef.current) {
          logoRef.current.material = customLogoMaterial;
        }
      });
    }else if(logoRef.current) {
      logoRef.current.material = nodes.Plane.material.clone();
    }
  }, [customLogoUrl, nodes.Plane.material]);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={scale}
      position={position}
      rotation={rotation}
    >
      <mesh
        geometry={nodes.bottle.geometry}
        material={bodyMaterial}
        rotation={[Math.PI / 2, 0, 0]}
      />
      {labelVisible && (
        <mesh
          ref={labelRef}
          geometry={nodes.label.geometry}
          material={nodes.label.material}
          position={[0.013, 2.069, 0]}
          rotation={[-0.017, 0, 0]}
          scale={[0.876, 0.945, 0.877]}
        />
      )}
      {logoVisible && (
        <mesh
          ref={logoRef}
          geometry={nodes.Plane.geometry}
          material={customLogoUrl ? baseLogoMaterial : nodes.Plane.material}
          position={[0.026, 3, -1.13]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.138, 1, 0.285]}
        />
      )}    
    </group>
  )
}

useGLTF.preload(MODEL_PATH);


{/* <group {...props} dispose={null}>
      <mesh geometry={nodes.bottle.geometry} material={materials.mat0} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.label.geometry} material={nodes.label.material} position={[0.013, 2.069, 0]} rotation={[-0.017, 0, 0]} scale={[0.876, 0.945, 0.877]} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0.026, 2.608, -1.13]} rotation={[Math.PI / 2, 0, 0]} scale={[1.138, 1, 0.485]} />
    </group> */}